name: on-demand-build-staging
on:
  workflow_dispatch:
    inputs:
      build-git-sha:
        type: string
        description: Commit sha which is to be deployed to staging

permissions:
  id-token: write
  contents: write
  issues: write
  pull-requests: write

jobs:
  # ensure all the deployment specs are available for staging.
  preflight-checks:
    runs-on: ubuntu-latest
    outputs:
      build_started_unix: ${{ steps.build-start-time.outputs.build_started_unix }}
      build_started_utc: ${{ steps.build-start-time.outputs.build_started_utc }}
      commitedat: ${{ steps.get-commit-time.outputs.commitedat }}
    #   staging-deploy-specs: ${{ steps.get-deployment-specs.outputs.staging-deploy-specs }}
    steps:
      - name: build-start-time
        id: build-start-time
        shell: bash
        run: |
          echo "here"
        