---
    name: (Release) Cherry-Pick to Release
    
    on:
      workflow_dispatch:
        inputs:
          pr-numbers:
            description: PR number delimited by space - containing hotfix commits
            required: true
            type: string
          allow_merge_strategy_theirs:
            description: Allow merge strategy theirs during cherry-picks
            type: boolean
            required: false
            default: false
          dryrun:
            description: 'Dry run - print write cmds'
            type: boolean
            required: false
            default: false
    
    concurrency:
      group: ${{ github.workflow }}
    
    permissions:
      id-token: write
      actions: write
      contents: write
      checks: read
      statuses: read
      pull-requests: read
    
    jobs:
      summary-dry-run:
        runs-on: ubuntu-latest
        steps:
            - name: Test summary-dry-run
              run: echo ${{ github.event.inputs.pr-numbers }}


      push-rel-branch:
        name: Create Release
        runs-on: ubuntu-latest
        steps:
            - name: Create Release
              run: echo 'This is to Create cherry-pick Release'
              
      wait-for-images-to-build:
        runs-on: ubuntu-latest
        steps:
            - name: Test wait-for-images-to-build
              run: echo 'This is to test wait-for-images-to-build'

      tag-rc:
        runs-on: ubuntu-latest
        steps:
            - name: Test tag-rc
              run: echo 'This is to test tag-rc'

      wait-for-rc-and-summarize:
        runs-on: ubuntu-latest
        steps:
            - name: Test wait-for-rc-and-summarize
              run: echo 'This is to test wait-for-rc-and-summarize'

      deployment_approval:
        if:
          (github.event.inputs.dryrun != 'true')
        runs-on: ubuntu-latest
        environment:
          name: deploy
        steps:
        - name: Test approval
          run: echo 'This is to test approval'
