---
    name: (Release) Create Hotfix
    
    on:
      workflow_dispatch:
        inputs:
          pr-numbers:
            description: PR number delimited by space - containing hotfix commits
            required: true
            type: string
          allow_merge_strategy_theirs:
            description: Allow merge strategy theirs during cherry-picks
            type: boolean
            required: false
            default: false
          skip_rc_deploy:
            description: Skip an RC deploy because it will rollback test and cause disruptions
            type: boolean
            required: false
            default: false
          dryrun:
            description: 'Dry run - print write cmds'
            type: boolean
            required: false
            default: false
    
    concurrency:
      group: ${{ github.workflow }}
    
    permissions:
      id-token: write
      actions: write
      contents: write
      checks: read
      statuses: read
      pull-requests: read
    
    jobs:
      summary-dry-run:

      push-rel-branch:
        name: Start Hotfix Release
        # only run write commands if dryrun is not explicitly set

      wait-for-images-to-build:
        name: wait-for-images-to-build
    
      fake-rc-build-info-if-opted-in:
        name: fake-rc-build-info-if-opted-in

      tag-rc:
        name: tag-rc
    
      wait-for-rc-and-summarize:
        name: wait-for-rc-and-summarize